var stateData = {
	am: {
		name: 'Ape-Man',
		abbr: 'am',
		Description: 'He was an ape with dark blue fur, and was rather tall. He had sharp teeth, a big snout, and red pupils with yellow sclera',
		Personality: 'Agressive',
		AlterEgo: 'Carl, the stunt man on the movie',
		Downfall: 'Unmasked on camera',
		Why: 'Good old revenge. Carl did not get the lead role in the movie and he blamed that on Daphnes uncle. Carl then set about to ruin the movie',
	},
	bk: {
		name: 'Black knight',
		abbr: 'bk',
		Description: 'Large black suit of armour with red feathers on its helmet',
		Personality: 'Intimidating',
		AlterEgo: 'Mr.Wickles',
		Downfall: 'Fell into a trap',
		Why: 'To scare people away while he swapped the museums paintings with forgeries and selling the real paintings for profit',
	},
	cm: {
		name: 'Caveman',
		abbr: 'cm',
		Description: 'He had brownish skin and black shoulder-length hair. He wore a dark brown cloth around his waistline',
		Personality: 'Angry',
		AlterEgo: 'Professor Wayne',
		Downfall: 'Fell into a tank holding clam stuck',
		Why: 'Getting rid of a colleague and stealing his invention',
	},
	cr: {
		name: 'Charlie the Funland Robot',
		abbr: 'cr',
		Description: 'Charlie is a tall humanoid made of blue metal body and his eyes are bright yellow',
		Personality: 'mischevious and at times destructive',
		AlterEgo: 'Sarah Jenkins',
		Downfall: 'weakness was a powerful electromagnet',
		Why: 'Robots should not operate in a place where children were there to have fun',
	},
	cre: {
		name: 'Creeper',
		abbr: 'cre',
		Description: 'a green-skinned phantom/zombie, with dark red hair and yellow sclera. He wore a dark green trench coat, with dark green pants and black shoes',
		Personality: 'Violent temper',
		AlterEgo: 'Mr.Carswell',
		Downfall: 'Stuck in hay-bale making machine',
		Why: 'Robbing his own bank using the disguise to throw people off track',
	},
	dr: {
		name: 'Dracula',
		abbr: 'dr',
		Description: 'He resembled a human male, with pale skin, bowl-shaped black hair, pointy ears, and red sclera. He always had a smirky grin on his face. He wore a black cape, with a red interior, over a black suit',
		Personality: 'secretive, sneaky',
		AlterEgo: 'Big Bob Oakley',
		Downfall: 'Left behind clues in coffin',
		Why: 'Trying to scare people off so he could search for the Franken treasure alone',
	},
	fm: {
		name: 'Frankensteins Monster',
		abbr: 'fm',
		Description: 'He was a humanoid male, wtih jet black hair and yellow eyes. He had paleish green skin, and always had a scowl. He wore a dark blue coat, with a purple shirt underneath',
		Personality: 'secretive, sneaky',
		AlterEgo: 'Big Bob Oakley',
		Downfall: 'Left behind clues in coffin',
		Why: 'Trying to scare people off so he could search for the Franken treasure alone',
	},
	gcl: {
		name: 'Ghost Clown',
		abbr: 'gcl',
		Description: 'A stereotype clown with a evil grin on his face and his black eyeshadow',
		Personality: 'Likes to be In complete control',
		AlterEgo: 'Harry the Hypnotist',
		Downfall: 'Tries to hypnotize but was deflected and hypnotized himself into a chimpanzee',
		Why: 'Revenge against circus that sent him to prison for stealing',
	},
	gcc: {
		name: 'Ghost of Captain Cutler',
		abbr: 'gcc',
		Description: 'In a light green deep sea diving suit that was covered in a type of glowing seaweed',
		Personality: 'Very lifeless',
		AlterEgo: 'Captain Cutler',
		Downfall: 'Trapped unintentionally by Scooby',
		Why: 'Faked his death so that he could steal yachts',
	},
	gek: {
		name: 'Ghost of Elias Kingston',
		abbr: 'gek',
		Description: 'Middle-aged male, with blue skin and black hair',
		Personality: 'Intimidate',
		AlterEgo: 'Stuart Wetherby',
		Downfall: 'Use footage of the ghost himself with the special camera to frighten him into a trap',
		Why: 'Wanted to gain control of the family fortune and decided to get the fortune by tricking his family into giving it to him',
	},
	gg: {
		name: 'Ghost of Geronimo',
		abbr: 'gg',
		Description: 'A Native American carrying a tomahawk on horseback',
		Personality: 'Intimidate',
		AlterEgo: 'Buck Masters',
		Downfall: 'Use dogs to chase the witch doctor up a tree',
		Why: 'To kidnap all the dogs who might have beaten his own dog in the competition',
	},
	gmh: {
		name: 'Ghost of Mr.Hyde',
		abbr: 'gmh',
		Description: 'Green skin with big, white beady eyes, and long, dark gray hair and sported a long, dark green trench coat as well as a black, tight fitting hat',
		Personality: 'Sinister',
		AlterEgo: 'Dr.Jekyll',
		Downfall: 'Scare him with his costume making him fall through the trapdoor from earlier and onto a mattress and wrap him up, capturing him',
		Why: 'Used disguise to cover up his jewel thefts',
	},
	grb: {
		name: 'Ghost of Redbeard',
		abbr: 'grb',
		Description: 'Middle-aged male, with red beard, wore a black pirate hat with skull and crossbones, red coat with a pink interior, pink pants, and brown boots',
		Personality: 'Threaten and forced prisoners',
		AlterEgo: 'C.L. Magnus',
		Downfall: 'Ghost sword, Shaggy, Scooby and a jackhammer',
		Why: 'Was about to lose his business if he did not come up with some money. So he raided his own ships and was going to sell the cargo',
	},
	gzt: {
		name: 'Ghost of Zen Tuo',
		abbr: 'gzt',
		Description: 'Wore a white robe and coat that had green trimming decorating his coat and a white hood with a green hat that had a black brim',
		Personality: 'Obsessed, little patience',
		AlterEgo: 'A.FONG',
		Downfall: 'Captured accidently',
		Why: 'Ghost act was to scare people away from the temple, their center of the operation',
	},
	ggh: {
		name: 'Green Ghosts',
		abbr: 'ggh',
		Description: 'green robes with hoods over their heads shadowing their faces. They also wore gloves, with long, curved fingers',
		Personality: 'laughing sinisterly to scare',
		AlterEgo: 'Green robes with hoods over their heads shadowing their faces. They also wore gloves, with long, curved fingers and chains on wrists',
		Downfall: 'Trapped accidently',
		Why: 'Wanted the estate of Colonel Beauregard Sanders will, intimidate the inheritors to get the fortune themselves',
	},
	gy: {
		name: 'Gypsy',
		abbr: 'gy',
		Description: 'Elderly female, with black hair, pale skin, and red sclera. Wore traditional gypsy garb; a red turban, two large earrings, and orange and red clothing',
		Personality: 'Pretended to be a fortune teller',
		AlterEgo: 'Big Bob Oakley',
		Downfall: 'Left behind clues in coffin',
		Why: 'Trying to scare people off so he could search for the Franken treasure alone',
	},
	hs: {
		name: 'Headless Specter',
		abbr: 'hs',
		Description: 'No head and wore a mustard colored overcoat with a red interior. Also wears grey pants, and black shoes',
		Personality: 'Had an eerie laugh to intimidate',
		AlterEgo: 'Penrod Stillwall',
		Downfall: 'Crashed into a hen-house and trapped',
		Why: 'Made up the specter to scare people away to search for the treasure',
	},
	moa: {
		name: 'Mummy of Ankha',
		abbr: 'moa',
		Description: 'Mummy was covered in rolls of paper',
		Personality: 'Hostile and short-tempered',
		AlterEgo: 'Dr. Najib',
		Downfall: 'Lawn mower ride that lead to get caught in a basketball net',
		Why: 'Knew that Ankhas coin would unlock the latters most prized possession: a diamond scarab; hidden in a hippo statue',
	},
	ssk: {
		name: 'Spooky Space Kook',
		abbr: 'ssk',
		Description: 'Ghostly apparition of a humanoid male. A skull with huge, dull, pale yellow eyes, inside of a blue spacesuit',
		Personality: 'Intimidate',
		AlterEgo: 'Henry Bascombe',
		Downfall: 'Trapped in an air tunnel, the costume fell off, revealing his identity',
		Why: 'Scare the farmer and the Air Force into selling their lands cheap',
	},
	wp: {
		name: 'Wax Phantom',
		abbr: 'wp',
		Description: 'Nine-foot humanoid made of wax',
		Personality: 'Intimidate',
		AlterEgo: 'Roger stevens',
		Downfall: 'Trapped in the wax shower',
		Why: 'Embezzled a lot of money from the TV station and tryed to pin blame for theft and disappearance',
	}
};
